# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-tutorial',
                'doc_host': 'https://mehdiud.github.io',
                'git_url': 'https://github.com/mehdiud/nbdev-tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.classification': { 'nbdev_tutorial.classification.foo': ( 'classification.html#foo',
                                                                                      'nbdev_tutorial/classification.py'),
                                               'nbdev_tutorial.classification.say_hello': ( 'classification.html#say_hello',
                                                                                            'nbdev_tutorial/classification.py')},
            'nbdev_tutorial.exploratory_data_analysis': { 'nbdev_tutorial.exploratory_data_analysis.MyViz': ( 'dataset_exploration.html#myviz',
                                                                                                              'nbdev_tutorial/exploratory_data_analysis.py'),
                                                          'nbdev_tutorial.exploratory_data_analysis.MyViz.__init__': ( 'dataset_exploration.html#myviz.__init__',
                                                                                                                       'nbdev_tutorial/exploratory_data_analysis.py'),
                                                          'nbdev_tutorial.exploratory_data_analysis.MyViz.plot_stock': ( 'dataset_exploration.html#myviz.plot_stock',
                                                                                                                         'nbdev_tutorial/exploratory_data_analysis.py')}}}
